name: Fetch Variables for Main Branch

on:
  push:
    branches:
      - main

jobs:
  fetch-variables:
    runs-on: ubuntu-latest

    outputs:
      prod-repository: prod-shido-jenkins
      ecr-endpoint: 096085577054.dkr.ecr.us-east-1.amazonaws.com
      ecr-push-command: 'aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 096085577054.dkr.ecr.us-east-1.amazonaws.com'
