name: Fetch Variables and Trigger Build

on:
  push:
    branches:
      - main

jobs:
  fetch-variables:
    runs-on: ubuntu-latest
    outputs:
      prod-repository: ${{ steps.parse-vars.outputs.prod-repository }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch variables
        run: |
          # Run any script or command to fetch the variables you need
          # For example, if your variables are stored in a YAML file named 'variables.yaml'
          echo "Fetching variables..."
          cp .github/workflows/fetch_variables.yaml $GITHUB_WORKSPACE/fetch_variables.yaml

      - name: Parse variables
        id: parse-vars
        run: |
          # Here you can parse your variables.yaml file or fetch variables from any source
          # For demonstration purposes, let's just echo some values
          echo "::set-output name=prod-repository::prod-shido-jenkins"

      # Trigger the main workflow
      - name: Trigger Main Workflow
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: trigger-main-workflow
          commit-message: Trigger Main Workflow
          title: Trigger Main Workflow
          body: |
            This pull request is used to trigger the main workflow.
        env:
          PROD_REPOSITORY: ${{ steps.parse-vars.outputs.prod-repository }}
