name: Fetch Variables and Trigger Build

on:
  push:
    branches:
      - main

jobs:
  fetch-variables:
    runs-on: ubuntu-latest
    outputs:
      prod-repository: ${{ steps.parse-vars.outputs.prod-repository }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Parse variables
        id: parse-vars
        run: |
          # Here you can parse your variables.yaml file or fetch variables from any source
          # For demonstration purposes, let's just echo some values
          echo "::set-output name=prod-repository::prod-shido-jenkins"

      # Trigger the main workflow
      - name: Trigger Main Workflow
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await context.github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'main.yaml',
              ref: 'refs/heads/main',
              inputs: {
                PROD_REPOSITORY: '${{ steps.parse-vars.outputs.prod-repository }}'
              }
            });
            console.log(response);
