name: Fetch Variables and Trigger Build

on:
  push:
    branches:
      - main
      - stage

jobs:
  fetch-variables-main:
    runs-on: ubuntu-latest
    outputs:
      prod-repository: ${{ steps.parse-vars.outputs.prod-repository }}
      ecr-endpoint: ${{ steps.parse-vars.outputs.ecr-endpoint }}
      ecr-push-command: ${{ steps.parse-vars.outputs.ecr-push-command }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Load Variables
      - name: Load Variables
        id: load-variables
        run: |
          echo "WORKFLOW_FILE_PATH='.github/workflows/main.yaml'" >> $GITHUB_ENV

      # Parse variables for Main Branch
      - name: Parse variables - Main Branch
        id: parse-vars
        run: |
          if [[ "${{ github.ref }}" == 'refs/heads/main' ]]; then
            echo "::set-output name=prod-repository::prod-shido-jenkins"
            echo "::set-output name=ecr-endpoint::096085577054.dkr.ecr.us-east-1.amazonaws.com"
            echo "::set-output name=ecr-push-command::'aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 096085577054.dkr.ecr.us-east-1.amazonaws.com'"
          else
            echo "Skipping: Not main branch"
            exit 1
          fi

  fetch-variables-stage:
    runs-on: ubuntu-latest
    outputs:
      prod-repository: ${{ steps.parse-vars.outputs.prod-repository }}
      ecr-endpoint: ${{ steps.parse-vars.outputs.ecr-endpoint }}
      ecr-push-command: ${{ steps.parse-vars.outputs.ecr-push-command }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Load Variables
      - name: Load Variables
        id: load-variables
        run: |
          echo "WORKFLOW_FILE_PATH='.github/workflows/main.yaml'" >> $GITHUB_ENV

      # Parse variables for Stage Branch
      - name: Parse variables - Stage Branch
        id: parse-vars
        run: |
          if [[ "${{ github.ref }}" == 'refs/heads/stage' ]]; then
            echo "::set-output name=prod-repository::stage-shido-jenkins"
            echo "::set-output name=ecr-endpoint::096085577054.dkr.ecr.eu-west-1.amazonaws.com"
            echo "::set-output name=ecr-push-command::'aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 096085577054.dkr.ecr.eu-west-1.amazonaws.com'"
          else
            echo "Skipping: Not stage branch"
            exit 1
          fi
