name: Fetch Variables for Main Branch

on:
  push:
    branches:
      - main

jobs:
  fetch-variables:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}

      # Load Variables
      - name: Load Variables
        id: load-variables
        run: |
          echo "WORKFLOW_FILE_PATH='.github/workflows/main.yaml'" >> $GITHUB_ENV

      # Set outputs for Main Branch
      - name: Set Outputs - Main Branch
        id: set-outputs-main
        run: |
          echo "::set-output name=prod-repository::prod-shido-jenkins"
          echo "::set-output name=ecr-endpoint::096085577054.dkr.ecr.us-east-1.amazonaws.com"
          echo "::set-output name=ecr-push-command::'aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 096085577054.dkr.ecr.us-east-1.amazonaws.com'"
