name: Fetch Variables for Stage Branch

on:
  push:
    branches:
      - stage

jobs:
  fetch-variables:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/labeler@v4
        with:
          repository: ${{ github.repository }}


      # Load Variables
      - name: Load Variables
        id: load-variables
        run: |
          echo "WORKFLOW_FILE_PATH='.github/workflows/main.yaml'" >> $GITHUB_ENV

      # Set outputs for Stage Branch
      - name: Set Outputs - Stage Branch
        id: set-outputs-stage
        run: |
          echo "::set-output name=prod-repository::stage-shido-jenkins"
          echo "::set-output name=ecr-endpoint::096085577054.dkr.ecr.eu-west-1.amazonaws.com"
          echo "::set-output name=ecr-push-command::'aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 096085577054.dkr.ecr.eu-west-1.amazonaws.com'"
