name: Push the Docker image to AWS ECR Repos (Multi-Region)

on:
  push:
  
jobs:
  Fetch-Variables:
    name: Fetch Variables
    runs-on: ubuntu-latest
    steps:
      - name: Fetch variables
        uses: ./.github/workflows/fetch_variables.yaml
        id: vars

  Build-Prod-Main:
    name: Build and Push to Prod Region (us-east-1) - Main Branch
    runs-on: ubuntu-latest
    needs: [Fetch-Variables]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Continue with your build steps using the fetched variables
      - name: Configure AWS credentials (Prod Region)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR (Prod Region)
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR (Prod Region) - Main Branch
        env:
          ECR_ENDPOINT: ${{ needs.Fetch-Variables.outputs.ecr-endpoint }}
          ECR_REPOSITORY: ${{ needs.Fetch-Variables.outputs.prod-repository-main }}
          ECR_PUSH_COMMAND: ${{ needs.Fetch-Variables.outputs.ecr-push-command-main }}
        run: |
          # Use the fetched variables to build and push the Docker image
          echo "Building and pushing Docker image to ECR..."
          $ECR_PUSH_COMMAND $ECR_ENDPOINT/$ECR_REPOSITORY:latest

  Build-Prod-Stage:
    name: Build and Push to Prod Region (us-east-1) - Stage Branch
    runs-on: ubuntu-latest
    needs: [Fetch-Variables]
    if: github.ref == 'refs/heads/stage'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Continue with your build steps using the fetched variables
      - name: Configure AWS credentials (Prod Region)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Login to Amazon ECR (Prod Region)
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR (Prod Region) - Stage Branch
        env:
          ECR_ENDPOINT: ${{ needs.Fetch-Variables.outputs.ecr-endpoint }}
          ECR_REPOSITORY: ${{ needs.Fetch-Variables.outputs.prod-repository-stage }}
          ECR_PUSH_COMMAND: ${{ needs.Fetch-Variables.outputs.ecr-push-command-stage }}
        run: |
          # Use the fetched variables to build and push the Docker image
          echo "Building and pushing Docker image to ECR..."
          $ECR_PUSH_COMMAND $ECR_ENDPOINT/$ECR_REPOSITORY:latest
