name: Fetch Variables and Trigger Build

on:
  push:
    branches:
      - main
      - stage

jobs:
  fetch-variables:
    runs-on: ubuntu-latest

    outputs:
      prod-repository-main: ${{ steps.fetch-variables-main.outputs.prod-repository }}
      ecr-endpoint-main: ${{ steps.fetch-variables-main.outputs.ecr-endpoint }}
      ecr-push-command-main: ${{ steps.fetch-variables-main.outputs.ecr-push-command }}
      prod-repository-stage: ${{ steps.fetch-variables-stage.outputs.prod-repository }}
      ecr-endpoint-stage: ${{ steps.fetch-variables-stage.outputs.ecr-endpoint }}
      ecr-push-command-stage: ${{ steps.fetch-variables-stage.outputs.ecr-push-command }}

    steps:
      - name: Fetch Variables - Main Branch
        id: fetch-variables-main
        uses: ./.github/workflows/fetch_variables_main.yaml

      - name: Fetch Variables - Stage Branch
        id: fetch-variables-stage
        uses: ./.github/workflows/fetch_variables_stage.yaml

      - name: Checkout Repository
        uses: actions/checkout@v2

      # Login to Amazon ECR using the provided ECR credentials for Main Branch
      - name: Login to Amazon ECR - Main Branch
        id: login-ecr-main
        run: |
          eval "${{ steps.fetch-variables-main.outputs.ecr-push-command-main }}"

      # Login to Amazon ECR using the provided ECR credentials for Stage Branch
      - name: Login to Amazon ECR - Stage Branch
        id: login-ecr-stage
        run: |
          eval "${{ steps.fetch-variables-stage.outputs.ecr-push-command-stage }}"

      # Build and push Docker image for Main Branch
      - name: Build and Push Docker image - Main Branch
        run: |
          docker build -t ${{ steps.fetch-variables-main.outputs.prod-repository-main }} .
          docker tag ${{ steps.fetch-variables-main.outputs.prod-repository-main }}:latest ${{ steps.fetch-variables-main.outputs.ecr-endpoint-main }}/${{ steps.fetch-variables-main.outputs.prod-repository-main }}:latest
          docker push ${{ steps.fetch-variables-main.outputs.ecr-endpoint-main }}/${{ steps.fetch-variables-main.outputs.prod-repository-main }}:latest

      # Build and push Docker image for Stage Branch
      - name: Build and Push Docker image - Stage Branch
        run: |
          docker build -t ${{ steps.fetch-variables-stage.outputs.prod-repository-stage }} .
          docker tag ${{ steps.fetch-variables-stage.outputs.prod-repository-stage }}:latest ${{ steps.fetch-variables-stage.outputs.ecr-endpoint-stage }}/${{ steps.fetch-variables-stage.outputs.prod-repository-stage }}:latest
          docker push ${{ steps.fetch-variables-stage.outputs.ecr-endpoint-stage }}/${{ steps.fetch-variables-stage.outputs.prod-repository-stage }}:latest
