name: Fetch Variables and Trigger Build

on:
  push:
    #branches:
     # - main

jobs:
  fetch-variables:
    runs-on: ubuntu-latest
    outputs:
      prod-repository: ${{ steps.parse-vars.outputs.prod-repository }}

    steps:
      # First, checkout the repository to access the files
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Parse variables (in your actual workflow, replace this with your logic to fetch variables)
      - name: Parse variables
        id: parse-vars
        run: |
          # Here you can parse your variables.yaml file or fetch variables from any source
          # For demonstration purposes, let's just echo some values
          echo "::set-output name=prod-repository::prod-shido-jenkins"
